PREFIX onto: <http://www.ontotext.com/>
PREFIX pub-old: <http://ontology.ontotext.com/publishing#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX pub: <http://ontology.ontotext.com/taxonomy/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX ff-map: <http://factforge.net/ff2016-mapping/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?relativeEntity  (max(?name) as ?entityLabel) (xsd:integer(round((IF((?relWeight1 + ?relWeight2) > 0.9, 0, (?relWeight1 + ?relWeight2))*100))) as ?relativePopularity)
(sum(?rel_weight1) as ?relWeight1) (sum(?c1) as ?count1)
(sum(?rel_weight2) as ?relWeight2) (sum(?c2) as ?count2)
(count(*) as ?entityCount)
FROM onto:disable-sameAs
WHERE {
    {
        SELECT DISTINCT ?relativeEntity (sum(?weight) as ?rel_weight1) (count(*) as ?c1)  {
            {
                SELECT DISTINCT ?entity (max(?w1) as ?w2) {
                    ?news pub-old:creationDate ?date .
                    FILTER ((?date > "{min_date}T00:00:00Z"^^xsd:dateTime)  && (?date < "{max_date}T23:59:59Z"^^xsd:dateTime))
                    ?news pub-old:category ?category .
                    FILTER (?category = "{category}"^^xsd:string)
                    ?news pub-old:containsMention ?mention .
                    ?mention pub-old:hasInstance ?pub_entity ;
                        pub-old:relevanceScore ?relevance .
                    ?pub_entity pub:exactMatch ?entity .
                    ?entity a dbo:Agent .
                    BIND(?relevance as ?w1)
                } group by ?entity ?news
            }
            ?entity ff-map:agentRelation ?e2 ;
                ff-map:outDegree ?degree .
            BIND(?e2 as ?relativeEntity)
            BIND((?w2 / ?degree * "1.0"^^xsd:double) as ?weight)
        } group by ?relativeEntity ?entity
    }
    UNION
    {
        SELECT DISTINCT ?relativeEntity (sum(?weight) as ?rel_weight2) (count(*) as ?c2) {
            {
                SELECT DISTINCT ?entity (max(?w1) as ?w2) {
                    ?news pub-old:creationDate ?date .
                    FILTER ((?date > "{min_date}T00:00:00Z"^^xsd:dateTime)  && (?date < "{max_date}T23:59:59Z"^^xsd:dateTime))
                    ?news pub-old:category ?category .
                    FILTER (?category = "{category}"^^xsd:string)
                    ?news pub-old:containsMention ?mention .
                    ?mention pub-old:hasInstance ?pub_entity ;
                        pub-old:relevanceScore ?relevance .
                    ?pub_entity pub:exactMatch ?entity .
                    ?entity a dbo:Agent .
                    BIND(?relevance as ?w1)
                } group by ?entity ?news
            }
            ?entity ff-map:agentRelation ?e2 ;
                ff-map:outDegree ?degree1 .
            ?e2 ff-map:agentRelation ?e3 ;
                ff-map:outDegree ?degree2 .
            FILTER( ?e3 != ?entity )
            BIND(?e3 as ?relativeEntity)
            BIND((?w2 / ?degree1 / ?degree2 * "1.0"^^xsd:double) as ?weight)
        } group by ?relativeEntity ?entity
    }
    OPTIONAL {
        ?pub_entity2 pub:exactMatch ?relativeEntity .
        ?news2 pub-old:containsMention / pub-old:hasInstance ?pub_entity2 .
        ?news2 pub-old:creationDate ?date2 .
        FILTER ((?date2 > "{min_date}T00:00:00Z"^^xsd:dateTime)  && (?date2 < "{max_date}T23:59:59Z"^^xsd:dateTime))
        ?news2 pub-old:category ?category2 .
        FILTER (?category2 = "{category}"^^xsd:string)
    }
    FILTER(!bound(?news2))
    ?relativeEntity rdfs:label ?name .
}  GROUP BY ?relativeEntity
HAVING (?entityCount > 1)
ORDER BY desc(?relativePopularity)
LIMIT 100