PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX pub-old: <http://ontology.ontotext.com/publishing#>
PREFIX pub: <http://ontology.ontotext.com/taxonomy/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX ff-pub: <http://factforge.org/pub/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?entityLabel ?mentionedLodEntity (?numOfMentions AS ?relativePopularity)
FROM onto:disable-sameAs
WHERE {
    {
        SELECT ?pubEntity ?entityLabel ?mentionedLodEntity
        (count(*) AS ?numOfMentions) (sum(?relevance)/?numOfMentions AS ?averageRelevance)
        WHERE {
            ?news pub-old:containsMention ?mention.
            ?mention  pub-old:hasInstance ?pubEntity .
            ?mention pub-old:relevanceScore ?relevance.
            ?pubEntity pub:preferredLabel ?entityLabel.
            ?pubEntity pub:exactMatch ?mentionedLodEntity.
            ?mentionedLodEntity a owl:Thing .
            ?news pub-old:creationDate ?date.
            FILTER ((?date > "{min_date}T00:00:00Z"^^xsd:dateTime) && (?date < "{max_date}T23:59:00Z"^^xsd:dateTime))
            FILTER (?pubEntity != <http://ontology.ontotext.com/resource/tslhir2hhreo>) # CONFIG.SYS: DSP-1404
            ?news pub-old:category ?category .
            FILTER (?category = "{category}"^^xsd:string)
        } GROUP BY ?pubEntity ?entityLabel ?mentionedLodEntity
    }
} ORDER BY desc(?relativePopularity) limit 100