PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX onto: <http://www.ontotext.com/>
PREFIX pub-old: <http://ontology.ontotext.com/publishing#>
PREFIX pub: <http://ontology.ontotext.com/taxonomy/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ff-map: <http://factforge.net/ff2016-mapping/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?newsTitle ?newsDate ?news ?relEntity ?intermedEntity
FROM onto:disable-sameAs
WHERE {
    {
        SELECT distinct ?news ?newsDate ?newsTitle ?relEntity  {
            BIND(<{entity}>  as ?entity)
            ?news pub-old:creationDate ?newsDate .
            FILTER ((?newsDate > "{min_date}T00:00:00Z"^^xsd:dateTime) && (?newsDate < "{max_date}T23:59:59Z"^^xsd:dateTime))
            ?news pub-old:category ?category .
            FILTER (?category = "{category}"^^xsd:string)
            ?news pub-old:containsMention / pub-old:hasInstance ?pubEntity .
            ?pubEntity pub:exactMatch ?relEntity .
            ?relEntity ff-map:agentRelation ?entity .
            ?news pub-old:title ?newsTitle .
        } GROUP BY ?news ?newsDate ?newsTitle ?relEntity
    }
    UNION
    {
        SELECT ?news ?newsDate ?newsTitle ?relEntity ?intermedEntity {
            BIND(<{entity}> as ?entity)
            ?news pub-old:creationDate ?newsDate .
            FILTER ((?newsDate > "{min_date}T00:00:00Z"^^xsd:dateTime) && (?newsDate < "{max_date}T23:59:59Z"^^xsd:dateTime))
            ?news pub-old:category ?category .
            FILTER (?category = "{category}"^^xsd:string)
            ?news pub-old:containsMention / pub-old:hasInstance ?pubEntity .
            ?pubEntity pub:exactMatch ?relEntity .
            ?relEntity ff-map:agentRelation ?intermedEntity .
            ?intermedEntity ff-map:agentRelation ?entity .
            FILTER( ?relEntity != ?entity )
            ?news pub-old:title ?newsTitle .
        } GROUP BY ?news ?newsDate ?newsTitle ?relEntity ?intermedEntity
    }
} ORDER BY ?newsDate