PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX onto: <http://www.ontotext.com/>
PREFIX pub-old: <http://ontology.ontotext.com/publishing#>
PREFIX pub: <http://ontology.ontotext.com/taxonomy/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ff-map: <http://factforge.net/ff2016-mapping/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?title ?date ?news ?rel_entity ?intermed_entity
FROM onto:disable-sameAs
WHERE {
    {
        SELECT distinct ?news ?date ?title ?rel_entity  {
            BIND(<{entity}>  as ?entity)
            ?news pub-old:creationDate ?date .
            FILTER ((?date > "{min_date}T00:00:00Z"^^xsd:dateTime) && (?date < "{max_date}T23:59:59Z"^^xsd:dateTime))
            ?news pub-old:category ?category .
            FILTER (?category = "{category}"^^xsd:string)
            ?news pub-old:containsMention / pub-old:hasInstance ?pub_entity .
            ?pub_entity pub:exactMatch ?rel_entity .
            ?rel_entity ff-map:agentRelation ?entity .
            ?news pub-old:title ?title .
        } GROUP BY ?news ?date ?title ?rel_entity
    }
    UNION
    {
        SELECT ?news ?date ?title ?rel_entity ?intermed_entity {
            BIND(<{entity}> as ?entity)
            ?news pub-old:creationDate ?date .
            FILTER ((?date > "{min_date}T00:00:00Z"^^xsd:dateTime) && (?date < "{max_date}T23:59:59Z"^^xsd:dateTime))
            ?news pub-old:category ?category .
            FILTER (?category = "{category}"^^xsd:string)
            ?news pub-old:containsMention / pub-old:hasInstance ?pub_entity .
            ?pub_entity pub:exactMatch ?rel_entity .
            ?rel_entity ff-map:agentRelation ?intermed_entity .
            ?intermed_entity ff-map:agentRelation ?entity .
            FILTER( ?rel_entity != ?entity )
            ?news pub-old:title ?title .
        } GROUP BY ?news ?date ?title ?rel_entity ?intermed_entity
    }
} ORDER BY ?date